import { notFound } from "next/navigation";
import { MarketingPage } from "@/components/MarketingPage";

const pages = {
  download: { title: "Tools for a more connected life.", intro: "Meet Rylo's suite of products, thoughtfully designed to make hearing, communication, and connection feel effortless.", image: "/images/features-sky-poster.C3gIlTJ2_1a8P4o.avif", blocks: [{ title: "One place for every conversation.", body: "From live captions to personalized hearing support, Rylo brings the essentials together in one calm, clear experience." }, { title: "Made to move with you.", body: "Beautiful technology should fit into your life, not ask you to change it." }, { title: "Start with what you need.", body: "Explore products built around the ways you listen, speak, and connect." }] },
  "live-transcribe": { title: "Every word, right when you need it.", intro: "Live Transcribe turns speech into clear, readable captions in real time, wherever conversation takes you.", image: "/images/hero-cover-sky.BcA_18qB_ZMsrjM.avif", blocks: [{ title: "A clearer view of the moment.", body: "Follow along with natural, accurate transcription that keeps pace with real life." }, { title: "Private by design.", body: "Your conversations stay yours, with thoughtful controls and a focused interface." }, { title: "Built for everyday use.", body: "Meetings, dinners, appointments, and everything in between." }] },
  sidekick: { title: "A little help goes a long way.", intro: "Sidekick is a friendly conversation companion that helps you feel prepared, confident, and connected.", image: "/images/cta-couple-phone.DDfwRSnv_Z1Q42Ao.avif", blocks: [{ title: "Confidence in your pocket.", body: "Keep context close and let Sidekick help you navigate the moments that matter." }, { title: "Designed around you.", body: "Personalized support without getting in the way of being present." }, { title: "Connection, made simpler.", body: "Small tools. Big difference." }] },
  sign: { title: "Language without limits.", intro: "Rylo Sign helps people discover, learn, and communicate through American Sign Language.", image: "/images/sign-white-paper-handshapes.Dw3-dCgl_21y5HN.avif", blocks: [{ title: "The right word is always close.", body: "Explore a growing dictionary of signs and ideas with a visual, intuitive experience." }, { title: "Translate the way you think.", body: "Move between English and ASL with tools made for real communication." }, { title: "Built with the community.", body: "Created alongside Deaf people, for more meaningful connection." }] },
  "hearing-test": { title: "Understand your hearing.", intro: "A simple, guided hearing test that helps you learn more about how you experience sound.", image: "/images/hero-sky-background.qaFu5Zgx_1wsytD.avif", blocks: [{ title: "A few quiet minutes.", body: "Take the first step with a test designed to be clear and approachable." }, { title: "Results you can understand.", body: "No confusing jargon. Just useful information about your hearing." }, { title: "Support for what comes next.", body: "Bring your questions to a professional or explore tools that fit." }] },
  about: { title: "Designing a world that listens.", intro: "Rylo is a team of designers, technologists, and advocates building a more inclusive future for communication.", image: "/images/about-team.8c_2zkgR_Z70P5v.avif", blocks: [{ title: "Accessibility is the starting point.", body: "We build with the people who use our products, not around them." }, { title: "Technology can feel human.", body: "Our work is considered, warm, and made to live in the real world." }, { title: "Come build with us.", body: "The best ideas come from many perspectives." }] },
  careers: { title: "Come build what matters.", intro: "Join a small, ambitious team making everyday connection more accessible for everyone.", image: "/images/about-team.8c_2zkgR_Z70P5v.avif", blocks: [{ title: "Bring your whole self.", body: "We value curiosity, care, and lived experience as much as a perfect résumé." }, { title: "Do work with a point of view.", body: "Move quickly, sweat the details, and make things people genuinely want to use." }, { title: "Find your place at Rylo.", body: "Reach out and tell us what you could bring to the team." }] },
  blog: { title: "Stories worth hearing.", intro: "Ideas, field notes, and practical guides from the people making communication more accessible.", image: "/images/blog-how-to-call-a-deaf-person-on-the-phone.BL0W2BRJ_IgyYE.webp", blocks: [{ title: "The better conversation.", body: "Thoughts on listening, access, and the small choices that help everyone take part." }, { title: "Practical guides.", body: "Clear, useful resources for hearing loss, ASL, and inclusive communication." }, { title: "From the Rylo team.", body: "A closer look at what we are building and why." }] },
} as const;

export function generateStaticParams() { return Object.keys(pages).map((slug) => ({ slug })); }
export default async function SlugPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = pages[slug as keyof typeof pages]; if (!page) notFound(); return <MarketingPage {...page} />; }
